# Generated by Django 4.0.4 on 2022-05-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_stories_kids_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='synced',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='yu'),
        ),
    ]
