# Generated by Django 4.0.4 on 2022-05-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_stories_synced"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="time",
            field=models.CharField(
                max_length=1000, null=True, verbose_name="Date created"
            ),
        ),
        migrations.AlterField(
            model_name="stories",
            name="descendants",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Descendants"
            ),
        ),
    ]
