# Generated by Django 4.0.4 on 2022-05-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_stories_options_alter_stories_synced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stories',
            old_name='synced',
            new_name='syn',
        ),
    ]
