# Generated by Django 3.2.13 on 2022-05-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0008_rename_syn_stories_synced"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stories",
            name="url",
            field=models.URLField(
                blank=True, max_length=1000, null=True, verbose_name="URL"
            ),
        ),
    ]
